on:
   push:
     branches: [master]
   pull_request:
     branches: [master]  



jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
       
        - name: Deploy to Server
          uses: appleboy/scp-action@master
          env:
           HOST: ${{ secrets.REMOTE_HOST }}
           USERNAME: ${{ secrets.REMOTE_USER }}
           PORT: ${{ secrets.REMOTE_PORT }}
           KEY: ${{ secrets.SERVER_SSH_KEY }}
          with:
           source: "."
           target: "/home/o.olusgeun/test"
