on:
   push:
     branches: [master]
   pull_request:
     branches: [master]  



jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
       
        - name: Deploy to Server
          uses: easingthemes/ssh-deploy@main
          env:
              SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
              ARGS: "-rltgoDzvO --delete"
              SOURCE: "dist/"
              REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
              REMOTE_USER: ${{ secrets.REMOTE_USER }}
              REMOTE_PORT: $${{ secrets.REMOTE_PORT }}
              TARGET: ${{ secrets.REMOTE_TARGET }}
              EXCLUDE: "/dist/, /node_modules/"
